[[redirects]]
  from = "#"
  to = "https://affiliateleadmarketing.com"
  status = 200
  [[plugins]]
  package = "@netlify/plugin-gatsby"
[[headers]]
  from = "/*"
  to = "flask-rest-alm-admin.herokuapp.com/*"
  status = 200
   [headers.values]
      Access-Control-Allow-Origin = "*"