[[redirects]]
  from = "#"
  to = "https://affiliateleadmarketing.com"
  status = 200
  [[plugins]]
  package = "@netlify/plugin-gatsby"
[[headers]]
   for = "/*"
   [headers.values]
      Access-Control-Allow-Origin = "*"