[[redirects]]
  from = "#"
  to = "https://affiliateleadmarketing.com"
  status = 200
  [[plugins]]
  package = "@netlify/plugin-gatsby"
[[redirects]]
  from = "/almaccount/*"
  to = "https://flask-rest-alm-admin.herokuapp.com/textfile"
  status = 200
  [headers.values]
    Access-Control-Allow-Origin = "*"